data_path: /home/lvzhongjian/speed_prediction_in_road_network/data
suffix: 0123class_sub_region1
time_fill_split: 0.8
road_fill_split: 0.8
stride_sparse: True
stride_edges: 1
time_window: 20
use_loopup: True
no_adjacent_fill_zero: False

observe_length: 10
predict_length: 1
test_ratio: 0.2

model_name: LCRNN
model_path: /home/lvzhongjian/speed_prediction_in_road_network/model
use_cache_model: False

epochs: 500
batch_size: 48
early_stopping: 3
learning_rate: 0.0002

