data_path: /home/lvzhongjian/speed_prediction_in_road_network/data
suffix: 0123class_sub_region1
time_fill_split: 0.8
road_fill_split: 0.8
stride_sparse: True
stride_edges: 1
time_window: 5
start_hour: 8
end_hour: 22
no_adjacent_fill_zero: False
fix_adjacent_road_num: -1

observe_length: 10
predict_length: 1
test_ratio: 0.2

model_name: LCRNN
model_path: /home/lvzhongjian/speed_prediction_in_road_network/model
use_cache_model: True

epochs: 500
batch_size: 48
early_stopping: 3
learning_rate: 0.0002

